### ISSUE TITLE
bug: `docs/Push changes`  failed because permission denied

### ISSUE THREAD

**Issue by AbaoFromCUG** [ellisonleao/nvim-plugin-template#8]
### Did you check docs and existing issues?

- [X] I have read all the plugin docs
- [X] I have searched the existing issues
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

None

### Operating system/version

None

### Describe the bug

Thanks you for your work.

I create a plugin from you template, and push a commit to github, then the github action run failed.

https://github.com/AbaoFromCUG/rust-tools.nvim/actions/runs/5714642024/job/15482648839

What should I set in my repository? 

### Steps To Reproduce

None 

### Expected Behavior

Work right

**Comment by ellisonleao** [comment]
hey @AbaoFromCUG sorry for the late reply. I guess you already figured out the issue, right?

**Comment by AbaoFromCUG** [comment]
yeah, I setup repository's Workflow permissions, docs action need permission of repository, thanks
